name: Documentation

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish Documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          module-name: ModernAppKit
      - name: Upload documentation to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: ".build/documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
