name: Tests

on: [push]

jobs:
  test-macos:
    name: Run Tests
    runs-on: macos-latest

    steps:
      - name: Print Swift compiler version
        run: "swift --version"
      - uses: actions/checkout@v2
      - name: Run tests
        run: "swift test --parallel"
